---
- name: Playbook instalación Backend
  hosts: Frontend
  become: true
    
  tasks:
#-----------------------------------------------------Variables---------------------------------------------#
      - name: Variables
        ansible.builtin.include_vars:
          variables.yml
#-----------------------------------------------------------------------------------------------------------#

#----------------------Instalar funciones Frontend----------------------#
      - name: Actualizar repositorios
        ansible.builtin.apt:
          update_cache: true

      - name: Instalando servidor web Apache2.4
        apt:
          name: apache2
          state: present

      - name: Instalación PHP y sus módulos
        ansible.builtin.apt:
          name: "{{ item }}"
          state: present
        loop:
          - php
          - libapache2-mod-php
          - php-mysql

      - name: Instalar Python3
        ansible.builtin.apt:
          name: python3-pip
          state: present

      - name: Instalar Unzip
        ansible.builtin.apt:
          name: unzip
          state: present

#----------------------------------------------------------------------#

#-------------------------Instalar Wordpress--------------------------#
      - name: Descargar ultima versión wordpress
        ansible.builtin.get_url:
          url: https://wordpress.org/latest.zip
          dest: /tmp/
          
      - name: Eliminar carpeta wordpress
        ansible.builtin.file:
          path: /var/www/html/wordpress
          state: absent

      - name: Eliminar archivo index.html
        ansible.builtin.file:
          path: /var/www/html/index.html
          state: absent
          
      - name: Extraer archivo latest.zip
        ansible.builtin.unarchive:
          src: /tmp/wordpress-6.1.1.zip
          dest: /var/www/html
          remote_src: yes

      - name: Copiar archivo wp-config-sample.php
        ansible.builtin.copy:
          src: /var/www/html/wordpress/wp-config-sample.php
          dest: /var/www/html/wordpress/wp-config.php
          remote_src: yes

#------------------ Seds para cambiar variables------------------#
      - name: Establecer variables de configuración DB_NAME
        shell: sed -i "s/database_name_here/"{{ DB_NAME }}"/" /var/www/html/wordpress/wp-config.php
      - name: Establecer variables de configuración DB_USER
        shell: sed -i "s/username_here/"{{ DB_USER }}"/" /var/www/html/wordpress/wp-config.php
      - name: Establecer variables de configuración DB_PASSWORD
        shell: sed -i "s/password_here/"{{ DB_PASSWORD }}"/" /var/www/html/wordpress/wp-config.php
      - name: Establecer variables de configuración IP_DB
        shell: sed -i "s/localhost/"{{ DB_HOST }}"/" /var/www/html/wordpress/wp-config.php

      - name: Añadir variable WP_HOME
        shell: sed -i "/DB_COLLATE/a define('WP_HOME', '"{{ WP_HOME }}"');" /var/www/html/wordpress/wp-config.php
      
      - name: Añadir variable WP_SITEURL
        shell: sed -i "/WP_HOME/a define('WP_SITEURL', '"{{ WP_SITEURL }}"');" /var/www/html/wordpress/wp-config.php

#----------------------------------------------------------------#
      - name: Copiar el index de Wordpress
        ansible.builtin.copy:
          src: /var/www/html/wordpress/index.php
          dest: /var/www/html/index.php
          remote_src: yes
          
      - name: Copiamos 000-default.conf template y reemplazamos en config de apache2
        ansible.builtin.template:
          src: ../templates/000-default.conf.j2
          dest: /etc/apache2/sites-available

      - name: Copiamos dir.conf template y reemplazamos en config de apache2
        ansible.builtin.template:
          src: ../templates/dir.conf.j2
          dest: /etc/apache2/mods-available

      - name: Cambiar Header php de wordpress
        shell: sed -i "s|wp-blog-header.php|wordpress/wp-blog-header.php|" /var/www/html/index.php

      - name: Modificar propietario y grupo
        ansible.builtin.file:
          path: /var/www/html
          owner: www-data
          group: www-data
          recurse: true

#----------------------------------------------------------------------#

      - name: Reiniciar Apache2.4
        service:
          name: apache2
          state: restarted