---
- name: Playbook despliegue Wordpress
  hosts: NFS
  become: true
    
  tasks:
#-----------------------------------------------------Variables---------------------------------------------#
      - name: Variables
        ansible.builtin.include_vars:
          variables.yml
#-----------------------------------------------------------------------------------------------------------#

#-------------------------Instalar Wordpress--------------------------#
      - name: Instalar Unzip
        ansible.builtin.apt:
          name: unzip
          state: present
      
      - name: Descargar ultima versión wordpress
        ansible.builtin.get_url:
          url: https://wordpress.org/latest.zip
          dest: /tmp/
          
      - name: Eliminar carpeta wordpress
        ansible.builtin.file:
          path: /var/www/html/wordpress
          state: absent

      - name: Eliminar archivo index.html
        ansible.builtin.file:
          path: /var/www/html/index.html
          state: absent
          
      - name: Extraer archivo latest.zip
        ansible.builtin.unarchive:
          src: /tmp/wordpress-6.1.1.zip
          dest: /var/www/html
          remote_src: yes

      - name: Copiar archivo wp-config-sample.php
        ansible.builtin.copy:
          src: /var/www/html/wordpress/wp-config-sample.php
          dest: /var/www/html/wordpress/wp-config.php
          remote_src: yes

#------------------ Seds para cambiar variables------------------#
      - name: Establecer variables de configuración DB_NAME
        shell: sed -i "s/database_name_here/"{{ DB_NAME }}"/" /var/www/html/wordpress/wp-config.php
      - name: Establecer variables de configuración DB_USER
        shell: sed -i "s/username_here/"{{ DB_USER }}"/" /var/www/html/wordpress/wp-config.php
      - name: Establecer variables de configuración DB_PASSWORD
        shell: sed -i "s/password_here/"{{ DB_PASSWORD }}"/" /var/www/html/wordpress/wp-config.php
      - name: Establecer variables de configuración IP_DB
        shell: sed -i "s/localhost/"{{ DB_HOST }}"/" /var/www/html/wordpress/wp-config.php

      - name: Copiar el index de Wordpress
        ansible.builtin.copy:
          src: /var/www/html/wordpress/index.php
          dest: /var/www/html/index.php
          remote_src: yes

      - name: Modificar el archivo wp-config.php
        ansible.builtin.blockinfile:
          path: /var/www/html/wordpress/wp-config.php
          insertafter: DB_COLLATE
          block: |
            define('WP_HOME', '{{ WP_HOME }}');
            define('WP_SITEURL', '{{ WP_SITEURL }}');

#----------------------------------------------------------------#

          
      - name: Modificación del archivo index.php
        ansible.builtin.replace:
          path: /var/www/html/index.php
          regexp: wp-blog-header.php
          replace: wordpress/wp-blog-header.php

      - name:  Cambiar función HTTPS de wp-config.php
        shell: sed -i "/WP_HOME/a $_SERVER['HTTPS'] = 'on';" /var/www/html/wordpress/wp-config.php

      - name: Modificar propietario y grupo
        ansible.builtin.file:
          path: /var/www/html
          owner: www-data
          group: www-data
          recurse: true

#----------------------------------------------------------------------#

      - name: Reiniciar servidor NFS
        ansible.builtin.service:
          name: nfs-kernel-server
          state: restarted

#----------------------------------------------------------------------#