---
- name: Playbook instalación pila LAMP
  hosts: Wordpress
  become: true
    
  tasks:
#-----------------------------------------------------Variables---------------------------------------------#
      - name: Variables
        ansible.builtin.include_vars:
          variables.yml
#-----------------------------------------------------------------------------------------------------------#

      - name: Actualizar repositorios
        ansible.builtin.apt:
          update_cache: true

      - name: Instalando servidor web Apache2.4
        apt:
          name: apache2
          state: present

      - name: Instalando sistema de base de datos MySQL
        apt:
          name: mysql-server
          state: present

      - name: Instalación PHP y sus módulos
        ansible.builtin.apt:
          name: "{{ item }}"
          state: present
        loop:
          - php
          - libapache2-mod-php
          - php-mysql

      - name: Activar modulo Apache2
        community.general.apache2_module:
          state: present
          name: "{{ item }}"
        loop:
          - rewrite

      - name: Copiamos 000-default.conf template y reemplazamos en config de apache2
        ansible.builtin.template:
          src: ../templates/000-default.conf.j2
          dest: /etc/apache2/sites-available

      - name: Copiamos dir.conf template y reemplazamos en config de apache2
        ansible.builtin.template:
          src: ../templates/dir.conf.j2
          dest: /etc/apache2/mods-available

      - name: Reiniciar Apache2.4
        service:
          name: apache2
          state: restarted