---
- name: Playbook instalación Loadbalancer
  hosts: Loadbalancer
  become: true
    
  tasks:
#-----------------------------------------------------Variables---------------------------------------------#
      - name: Variables
        ansible.builtin.include_vars:
          variables.yml
#-----------------------------------------------------------------------------------------------------------#